services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - layservicesnetwork

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    tty: true
    volumes:
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf 
    networks:
      - layservicesnetwork
    mem_limit: 4g
    expose:
      - 6379
      
configs:
  qdrant_config:
    content: |
      log_level: INFO
networks:
  layservicesnetwork:
    driver: bridge
