FROM nikolaik/python-nodejs

WORKDIR /app

COPY . /app

RUN npm install @modelcontextprotocol/inspector@0.8.2

RUN pip install uv

RUN uv venv

RUN uv sync --only-group fastmcp

CMD ["uv", "run", "--only-group", "fastmcp", "fastmcp", "dev", "server.py"]
