FROM python:3.12-slim

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    python3-dev \
    build-essential 
    
RUN pip install uv

RUN uv venv

RUN uv sync --only-group fastmcp

CMD ["uv", "run", "fastmcp", "dev", "server.py"]
