"""Migration for models

Revision ID: 0d572b6f8d24
Revises: de205cf4a53c
Create Date: 2025-04-16 13:26:59.282325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d572b6f8d24'
down_revision: Union[str, None] = 'de205cf4a53c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logrhythm_alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_rule_id', sa.String(length=36), nullable=True),
    sa.Column('alarm_id', sa.String(length=36), nullable=True),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('alarm_date', sa.DateTime(), nullable=True),
    sa.Column('alarm_status_name', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('alarm_rule_name', sa.String(length=255), nullable=True),
    sa.Column('last_updated_id', sa.String(length=36), nullable=True),
    sa.Column('last_updated_name', sa.String(length=255), nullable=True),
    sa.Column('date_inserted', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('associated_cases', sa.JSON(), nullable=True),
    sa.Column('last_person_id', sa.String(length=36), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('event_date_first', sa.DateTime(), nullable=True),
    sa.Column('event_date_last', sa.DateTime(), nullable=True),
    sa.Column('rbp_max', sa.Float(), nullable=True),
    sa.Column('rbp_avg', sa.Float(), nullable=True),
    sa.Column('smart_response_actions', sa.JSON(), nullable=True),
    sa.Column('alarm_data_cached', sa.Boolean(), nullable=True),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('classification_name', sa.String(length=100), nullable=True),
    sa.Column('classification_type_name', sa.String(length=100), nullable=True),
    sa.Column('command', sa.String(length=500), nullable=True),
    sa.Column('common_event_id', sa.Integer(), nullable=True),
    sa.Column('common_event_name', sa.String(length=255), nullable=True),
    sa.Column('impacted_entity_id', sa.Integer(), nullable=True),
    sa.Column('impacted_entity_name', sa.String(length=255), nullable=True),
    sa.Column('impacted_host_name', sa.String(length=255), nullable=True),
    sa.Column('impacted_ip', sa.String(length=50), nullable=True),
    sa.Column('impacted_zone', sa.String(length=100), nullable=True),
    sa.Column('impacted_port', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.DateTime(), nullable=True),
    sa.Column('log_source_host_name', sa.String(length=255), nullable=True),
    sa.Column('log_source_name', sa.String(length=255), nullable=True),
    sa.Column('log_source_type_name', sa.String(length=255), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('process', sa.String(length=255), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logrhythm_alarms')
    # ### end Alembic commands ###
