"""Add Fiels into Logrhythm alert

Revision ID: 4aa9fd53c484
Revises: 94f63ef059ed
Create Date: 2025-04-17 11:44:29.496772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa9fd53c484'
down_revision: Union[str, None] = '94f63ef059ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logrhythm_alarms', sa.Column('model_classification', sa.String(length=10), nullable=True))
    op.add_column('logrhythm_alarms', sa.Column('real_classification', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logrhythm_alarms', 'real_classification')
    op.drop_column('logrhythm_alarms', 'model_classification')
    # ### end Alembic commands ###
